In [36]:
import numpy as np

get_skew = lambda a: np.array([[ 0, -a[2, 0], a[1, 0]], [a[2, 0], 0, -a[0, 0]], [-a[1, 0], a[0, 0], 0]])

# Define the rotation matrices for each axis

def get_x_rotation_matrix(theta, is_hybrid = False):
    
    if is_hybrid:
        return np.array([
            [1, 0, 0, 0],
            [0, np.cos(theta), -np.sin(theta), 0],
            [0, np.sin(theta), np.cos(theta), 0],
            [0, 0, 0, 1]
        ])
    else:
        return np.array([[1, 0, 0],
                        [0, np.cos(theta), -np.sin(theta)],
                        [0, np.sin(theta), np.cos(theta)]])
    
def get_y_rotation_matrix(theta, is_hybrid = False):
    if is_hybrid:
        return np.array([
        [np.cos(theta), 0, np.sin(theta), 0],
        [0, 1, 0, 0],
        [-np.sin(theta), 0, np.cos(theta), 0],
        [0, 0, 0, 1]
    ])
    else:
        return np.array([[np.cos(theta), 0, np.sin(theta)],
               [0, 1, 0],
               [-np.sin(theta), 0, np.cos(theta)]])
    
def get_z_rotation_matrix(theta, is_hybrid = False):
    if is_hybrid:
        return np.array([
            [np.cos(theta), -np.sin(theta), 0, 0],
            [np.sin(theta), np.cos(theta), 0, 0],
            [0, 0, 1, 0],
            [0, 0, 0, 1]
        ])
    else:      
        return np.array([[np.cos(theta), -np.sin(theta), 0],
                [np.sin(theta), np.cos(theta), 0],
                [0, 0, 1]])

## Q4.1

[![image.png](https://i.postimg.cc/8CtBNNFx/image.png)](https://postimg.cc/LqgZVd3V)

In [37]:
theta = np.array([[-0.12, -0.95, 0.03]])

# translate about z
joint_1 = np.array([
    [1, 0, 0, -2],
    [0, 1, 0, 2],
    [0, 0, 1, theta[0, 0]],
    [0, 0, 0, 1]
])


joint_2 = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 2],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
]) @ get_z_rotation_matrix(theta[0, 1], True)

joint_3 = np.array([
    [1, 0, 0, 2],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
]) @ get_z_rotation_matrix(theta[0, 2], True)


coordinate_transform = np.array([
    [0, 0, 1, 0],
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1]
])

translate_end = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 2],
    [0, 0, 0, 1]
])

T_0_1 = joint_1 @ joint_2 @ joint_3 @ coordinate_transform @ translate_end

T_0_1



array([[ 0.79560162,  0.        ,  0.60582016,  0.37500649],
       [ 0.60582016,  0.        , -0.79560162,  0.78196575],
       [ 0.        ,  1.        ,  0.        , -0.12      ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

[![image.png](https://i.postimg.cc/VsWxbHSg/image.png)](https://postimg.cc/xqqxw53N)

In [38]:
theta = np.array([[0.96, -0.35, 0.57]])

# translate about z
joint_1 = np.array([
    [1, 0, 0, -2],
    [0, 1, 0, 0],
    [0, 0, 1, theta[0, 0]],
    [0, 0, 0, 1]
])

# rotate about x
# * give -theta because we are rotating about -x
joint_2 = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, -2],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
]) @ get_x_rotation_matrix( - theta[0, 1], True)

# rotate about y
# * give -theta because we are rotating about -y
joint_3 = np.array([
    [1, 0, 0, -2],
    [0, 1, 0, -2],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
]) @ get_y_rotation_matrix(- theta[0, 2], True)

coordinate_transform = np.array([
    [1, 0, 0, 0],
    [0, -1, 0, 0],
    [0, 0, -1, 0],
    [0, 0, 0, 1]
])

translate_end = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 2],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])

T_0_1 = joint_1 @ joint_2 @ joint_3 @ coordinate_transform @ translate_end

T_0_1



array([[ 0.84190098,  0.        ,  0.53963205, -4.        ],
       [-0.18503865, -0.93937271,  0.288686  , -5.75749085],
       [ 0.50691562, -0.34289781, -0.7908588 , -0.41159123],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

[![image.png](https://i.postimg.cc/tTJyTfPv/image.png)](https://postimg.cc/DW9Rpxx1)

In [39]:
theta = np.array([[0.50, 0.43, 0.59]])

# rotate about -z
joint_1 = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 2],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
]) @ get_y_rotation_matrix(theta[0, 0], True)

# translate about -x
joint_2 = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 2],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
]) @ get_z_rotation_matrix( - theta[0, 1], True)

# translate about z
joint_3 = np.array([
    [1, 0, 0, 2],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
]) @ get_z_rotation_matrix( - theta[0, 2], True)

coordinate_transform = np.array([
    [0, -1, 0, 0],
    [-1, 0, 0, 0],
    [0, 0, -1, 0],
    [0, 0, 0, 1]
])

translate_end = np.array([
    [1, 0, 0, 2],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])

T_0_1 = joint_1 @ joint_2 @ joint_3 @ coordinate_transform @ translate_end

T_0_1



array([[-0.74779514, -0.45929683, -0.47942554,  0.0997947 ],
       [-0.52336595,  0.85210802,  0.        ,  2.11952649],
       [ 0.40852235,  0.250915  , -0.87758256, -0.05451809],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

[![image.png](https://i.postimg.cc/wxPJ6YJP/image.png)](https://postimg.cc/hhLhrw2b)

In [40]:
theta = np.array([[0.97, 0.37, -0.76]])

# rotate about -z
joint_1 = np.array([
    [1, 0, 0, theta[0, 0]],
    [0, 1, 0, 0],
    [0, 0, 1, -2],
    [0, 0, 0, 1]
])

# translate about -x
joint_2 = np.array([
    [1, 0, 0, 2],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
]) @ get_y_rotation_matrix(theta[0, 1], True)

# translate about z
joint_3 = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, theta[0, 2]],
    [0, 0, 1, 2],
    [0, 0, 0, 1]
])

coordinate_transform = np.array([
    [0, 0, 1, 0],
    [-1, 0, 0, 0],
    [0, -1, 0, 0],
    [0, 0, 0, 1]
])

translate_end = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 2],
    [0, 0, 0, 1]
])

T_0_1 = joint_1 @ joint_2 @ joint_3 @ coordinate_transform @ translate_end

T_0_1



array([[ 0.        , -0.36161543,  0.93232735,  5.55788556],
       [-1.        ,  0.        ,  0.        , -0.76      ],
       [ 0.        , -0.93232735, -0.36161543, -0.85857617],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])