## HW1 helper functions

In [2]:
from __future__ import print_function

# setup some librairies and display options
%matplotlib notebook

import numpy as np
import matplotlib.pyplot as plt

# be careful we will only print the first 5 digits and round small numbers in arrays
np.set_printoptions(suppress=True, precision=5)

# libraries to make things interactive
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
from IPython.display import display, Latex, Markdown

# a nice function to print pretty matrices in latex
def bmatrix(a):
    """Returns a LaTeX bmatrix

    :a: numpy array
    :returns: LaTeX bmatrix as a string
    """
    if len(a.shape) > 2:
        raise ValueError('bmatrix can at most display two dimensions')
    lines = str(a).replace('[', '').replace(']', '').splitlines()
    rv = [r'\begin{bmatrix}']
    rv += ['  ' + ' & '.join(l.split()) + r'\\' for l in lines]
    rv +=  [r'\end{bmatrix}']
    return str(''.join(rv))

def pmatrix(a):
    """Returns a LaTeX bmatrix

    :a: numpy array
    :returns: LaTeX bmatrix as a string
    """
    if len(a.shape) > 2:
        raise ValueError('bmatrix can at most display two dimensions')
    lines = str(a).replace('[', '').replace(']', '').splitlines()
    rv = [r'\begin{pmatrix}']
    rv += ['  ' + ' & '.join(l.split()) + r'\\' for l in lines]
    rv +=  [r'\end{pmatrix}']
    return str(''.join(rv))

A rotation matrix can be used to describe the relative orientation of a frame with respect to another. Each column of a rotation matrix contains to the coordinates of one axis of the rotated frame with respect to the original frame.

Rotation matrices are typically used for three different purposes
1. To describe the orientation of a frame with respect to another
2. To rotate a point, a vector or a rigid body
3. To change coordinates

We give example of all of these uses in 2D below

# Rotations in 2D
The only possible rotations in 2D are rotations around an axis orthogonal to the plane. A rotation of $\theta$  can be written as the rotation matrix $$R(\theta) = \begin{bmatrix} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{bmatrix}$$

First we write a function that creates a 2D rotation matrix

In [3]:

def get_rotation_2D(theta, is_x_reflected=False, is_y_reflected=False):
    """This function gets an angle and returns a rotation matrix representing a 2D rotation of theta"""
    
    # TODO if is_x_reflected and is_y_reflected:
        
    
    if is_y_reflected:
        return np.array([[np.cos(theta), -np.sin(theta)],[np.sin(theta), np.cos(theta)]]) * np.array([[1, 0], [0, -1]])
    
    if is_x_reflected:
        return np.array([[np.cos(theta), -np.sin(theta)],[np.sin(theta), np.cos(theta)]]) *  np.array([[-1, 0], [0, 1]])
    
    return np.array([[np.cos(theta), -np.sin(theta)],[np.sin(theta), np.cos(theta)]])

# we can get and print a rotation of theta=pi/4
R = get_rotation_2D(np.pi/6, is_y_reflected=True)

display(Markdown('we can get and print a rotation of ' + r'$\theta$'))
display(Markdown('$R = ' + bmatrix(R) + '$'))

we can get and print a rotation of $\theta$

$R = \begin{bmatrix}  0.86603 & -0.\\  0. & -0.86603\\\end{bmatrix}$

## Properties of rotation matrices
We can also verify that for any random $\theta$, the matrix is orthogonal and has determinant equal to 1

In [4]:
# TODO: uncomment
theta = ...
# R = get_rotation_2D(theta)


# * R1 = np.array([[-0.10761548, -0.41113130, -0.90520162], [0.98901804, -0.13704466, -0.05533607], [-0.10130266, -0.90121575, 0.42136439]])
# ! R2 = np.array([[-0.58009582, -0.22621631, 0.76238773], [-0.67848847, -0.31125822, -0.56780201], [0.64235080, -0.96794980, 0.14389378]])
# * R3 = np.array([[0.80573370, 0.11750521, -0.58050472], [-0.23580136, 0.96273803, -0.13241299], [0.54331475, 0.24357341, 0.80341837]])
# * R4 = np.array([[0.23249600, -0.18131522, -0.95554717], [-0.87464304, 0.39071662, -0.28694960], [0.42537649, 0.90247732, -0.06774604]])
# ! R5 = np.array([[0.69740483, -0.77430588, 0.38698850], [-0.48206339, -0.54297335, -0.68562213], [0.69782640, 0.14771323, -0.89303975]])


R = np.array([[0.69740483, -0.77430588, 0.38698850], [-0.48206339, -0.54297335, -0.68562213], [0.69782640, 0.14771323, -0.89303975]])


display(Markdown(r'$\theta$ = ' + f'{theta}\n'))
display(Markdown('$R = ' + bmatrix(R) + '$'))
display(Markdown('$R \cdot R^T = ' + bmatrix(R@R.T) + '$'))
display(Markdown('$R^T \cdot R = ' + bmatrix(R.T@R) + '$'))

print(f'det(R) = {np.linalg.det(R)}')

$\theta$ = Ellipsis


$R = \begin{bmatrix}  0.6974 & -0.77431 & 0.38699\\  -0.48206 & -0.54297 & -0.68562\\  0.69783 & 0.14771 & -0.89304\\\end{bmatrix}$

$R \cdot R^T = \begin{bmatrix}  1.23568 & -0.18109 & 0.0267\\  -0.18109 & 0.99728 & 0.19569\\  0.0267 & 0.19569 & 1.3063\\\end{bmatrix}$

$R^T \cdot R = \begin{bmatrix}  1.20572 & -0.17518 & -0.02279\\  -0.17518 & 0.91619 & -0.05929\\  -0.02279 & -0.05929 & 1.41736\\\end{bmatrix}$

det(R) = 1.231676393437032


### Problem 1.4

In [5]:
# * Variant 1

p_84 = np.array([[0.96086095], [-0.64535621]])
R_84 = np.array([[0.99996130, -0.00879799], [0.00879799, 0.99996130]])
q_8 = np.array([[-0.55744701], [-0.42409166]])

# q_8 into q_48
q_48 = R_84.dot(q_8)

q_44 = -p_84 + q_48

q_44

array([[-1.51456],
       [ 0.21638]])

In [6]:
# * Variant 2

p_46 = np.array([[-0.93881365], [0.25679497]])
R_46 = np.array([[0.35313045, 0.93557410], [-0.93557410, 0.35313045]])
q_6 = np.array([[-0.35183909], [0.62138823]])

# q_6 into q_46
q_46 = R_46.dot(q_6)

q_44 = p_46 + q_46
q_44

array([[-0.4817],
       [ 0.8054]])

### Problem 1.7

In [7]:
# * Variant 1

Borigin_A = p_94 = np.array([0.79114713, -0.14789957, -0.14998143])

# theta = np.pi/3

R_x = R_94 = np.array([[-0.00814677, 0.60918952, 0.79298282], [0.03074542, 0.79278682, -0.60872308], [-0.99949405, 0.01942146, -0.02518845]])
point = q_44 = np.array([[-0.67962356], [-0.98268493], [-0.96523565]])

# Find q_94
q_94 = np.dot(R_94, q_44) + p_94.reshape(3, 1)

q_94

array([[-0.56737],
       [-0.36029],
       [ 0.53453]])

In [8]:
# * offset of B origin from A origin
Borigin_A = p_60 = np.array([0.45805854, 0.54111007, -0.81941494])

# theta = np.pi/3

R_x = R_60 = np.array([[-0.96473218, 0.12134664, -0.23359540], [0.12911847, 0.99146193, -0.01821170], [0.22939102, -0.04773089, -0.97216332]])
point = q_00 = np.array([[0.90093863], [0.22937904], [0.81650240]])

# Find q_60
q_60 = np.dot(R_60, q_00) + p_60.reshape(3, 1)
q_60
# print(q_60)

array([[-0.574  ],
       [ 0.86999],
       [-1.41747]])

[![Screenshot-2023-02-05-104920.png](https://i.postimg.cc/25fxjs06/Screenshot-2023-02-05-104920.png)](https://postimg.cc/dh4C4xPP)

[![image.png](https://i.postimg.cc/CKPHCRFZ/image.png)](https://postimg.cc/nsmDpc9Z)

In [9]:
# ! variant 2

# * offset of B origin from A origin
Borigin_A = p_62 = np.array([-0.74646944, -0.52337828, 0.94708969])

# theta = np.pi/3

R_x = R_62 = np.array([[-0.53290233, -0.75344121, 0.38515121], [0.80708298, -0.31582559, 0.49886999], [-0.25422860, 0.57669796, 0.77639377]])
point = q_66 = np.array([[-0.36154442], [-0.53805158], [-0.70585669]])

# translate evertyhing to axis 2
q_26 = np.dot(R_62.T, q_66)  # inverse and then dot product
p_26 = np.dot(R_62.T, p_62.reshape(3, 1))

# now find the path in axis 2 using vector sum
path_in_axis_2 = q_26 - p_26

path_in_axis_2

array([[ 0.20326],
       [-1.23863],
       [-1.1424 ]])

In [10]:
# ! variant 2

# * offset of B origin from A origin
Borigin_A = p_87 = np.array([-0.44859274, 0.72677313, 0.06891165])

# theta = np.pi/3
R_x = R_87 = np.array([[0.77827776, 0.04352599, 0.62640978], [-0.53083687, -0.48725870, 0.69339107], [0.33540415, -0.87217226, -0.35611741]])

point = q_88 = np.array([[-0.52342082], [-0.95925166], [0.37552983]])

# translate evertyhing to axis 7
q_78 = np.dot(R_87.T, q_88) # inverse of R_87 and then dot product
p_78 = np.dot(R_87.T, p_87.reshape(3, 1))

# now find the path in axis 7 using vector sum
path_in_axis_7 = q_78 - p_78

path_in_axis_7

array([[ 0.93961],
       [ 0.55085],
       [-1.32514]])

In [11]:
# ! variant 2

# * offset of B origin from A origin
Borigin_A = p_14 = np.array([[-0.26454129], [0.41259182], [-0.84779370]])

# theta = np.pi/3
R_x = R_41 = np.array([[0.85049226, 0.52056708, -0.07531821], [0.24888631, -0.52443690, -0.81426134], [-0.46337730, 0.67377730, -0.57559155]])

point = q_44 = np.array([[-0.39428019], [-0.92702154], [-0.24232918]])

# translate evertyhing to axis 1
q_14 = np.dot(R_41.T, q_44)
p_14 = np.dot(R_41.T, p_14.reshape(3, 1))

# now find the path in axis 1 using vector sum
path_in_axis_1 = q_14 - p_14

path_in_axis_1

array([[-0.72431],
       [ 1.04295],
       [ 0.75207]])

### Problem 1.8

[![image.png](https://i.postimg.cc/ZnSzh8Rg/image.png)](https://postimg.cc/BLMVT12c)

[![image.png](https://i.postimg.cc/3xySnyrD/image.png)](https://postimg.cc/ZWSxq5dT)

In [23]:
# * offset of B origin from A origin
Borigin_A = o_9in5 = np.array([[0.55440778], [-0.76436229], [-0.78469475]])

# theta = np.pi/3
R_x = R_9in5 = np.array([[0.07155755, 0.13053746, 0.98885767], [0.99609913, -0.06067355, -0.06407215], [0.05163369, 0.98958511, -0.13436990]])

# point = q_44 = np.array([[-0.39428019], [-0.92702154], [-0.24232918]])

vector = v_5in5 = np.array([[-0.35180568], [0.16130314], [-0.31815458]])

# translate evertyhing to cooordinate 9
v_9in5 = np.dot(R_9in5.T, v_5in5)

v_9in5

array([[ 0.11907],
       [-0.37055],
       [-0.31547]])

### Problem 1.9

In [62]:
# * offset of B origin from A origin
Borigin_A = p_idk = np.array([0.21851409, -0.94158325, 0.19817520])

# theta = np.pi/3
R_x = R_idk = np.array([[0.84269460, -0.45480885, -0.28812276], [-0.50043488, -0.85906025, -0.10761234], [-0.19857177, 0.23487102, -0.95152764]])

point_1 = q1_in0 = np.array([[-1.35845114], [0.31505727], [-0.34374760]])

point_2 = q1_in1 = np.array([[-0.97049467], [-0.49542861], [0.86900841]])

point_3 = q2_in1 = np.array([[0.25434323], [0.89489765], [-0.15265953]])

possibilities = [(R_idk, p_idk), (R_idk.T, p_idk), (R_idk, -p_idk), (R_idk.T, -p_idk)]

for (R, p) in possibilities:
    zero_into_one = np.dot(R, point_1) + p.reshape(3, 1)
    
    if np.allclose(zero_into_one, point_2):
        print('found it')
        print(R)
        print(p)
        break
    
# Convert zero_into_one Rotation matrix and position vector to one_into_zero Rotation matrix and position vector

R_one_to_zero = R.T
p_one_to_zero = -np.dot(R.T, p)

q2_in0 = np.dot(R_one_to_zero, q2_in1) + p_one_to_zero.reshape(3, 1)
q2_in0

# q2_in1 = np.dot(R, q2_in1) + p.reshape(3, 1)
# q2_in1


found it
[[ 0.84269 -0.45481 -0.28812]
 [-0.50043 -0.85906 -0.10761]
 [-0.19857  0.23487 -0.95153]]
[ 0.21851 -0.94158  0.19818]


array([[-0.81918],
       [-1.67634],
       [ 0.12588]])